name: "[iOS] Build and Test App"

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: ./iOS

jobs:
  test:
    name: "Build iOSApp"
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: Install xcpretty
        run: bundle install
      - name: Setup
        run: make bootstrap
      - name: Copy file for CI
        working-directory: ./iOS/Pog/Pog/Env
        run: cp SecretSample.swift Secret.swift
      - name: Build and Test
        run: set -o pipefail && make clean build test | bundle exec xcpretty