name: Build And Test

on: pull_request

env:
    PRODUCT_NAME: PlaceDiary

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_11.3.app/Contents/Developer'
    - name: Show Xcode Version
      run: xcodebuild -version
    - uses: actions/cache@v1
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: Cocoapods
      if: steps.cache-cocoapods.outputs.cache-hit != 'true'
      run: pod install
    - name: Build
      run: xcodebuild -workspace $PRODUCT_NAME.xcworkspace -scheme $PRODUCT_NAME -sdk iphonesimulator -configuration Develop build 
    - name: Unit Test
      run: xcodebuild test -workspace $PRODUCT_NAME.xcworkspace -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 11" -scheme $PRODUCT_NAME -configuration Develop

